name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        dotnet: [ '2.2.108', '3.0.100' ]

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build with dotnet (Windows)
      run: dotnet build ./src/AspNetCore.Identity.DocumentDB -c Release
      if: matrix.os == 'windows-latest'
  
    - name: Build with dotnet (Unix)
      run: |
        dotnet build ./src/AspNetCore.Identity.DocumentDB -c Release -f netstandard1.6
        dotnet build ./src/AspNetCore.Identity.DocumentDB -c Release -f netstandard2.0
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
  
    - name: Test with dotnet (Windows)
      run: |
        dotnet test ./test/CoreTests -c Release $TEST_ARGS
        dotnet test ./test/CoreIntegrationTests -c Release -f netcoreapp2.0
      if: matrix.os == 'windows-latest'
  
    - name: Test with dotnet (Unix)
      run: |
        dotnet test ./test/CoreTests -c Release $TEST_ARGS
        dotnet test ./test/CoreIntegrationTests -c Release -f netcoreapp2.0 --filter Category!=BreaksUnix
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
 
    - name: Pack with dotnet
      run: dotnet pack ./src/AspNetCore.Identity.DocumentDB -c Release -o artifacts
  
    - uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: artifacts
